### ISSUE TITLE
Deployment Error - thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\lib.rs:29:22note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by GarnetSunset** [atampy25/simple-mod-framework#634]
Not sure what's going on but, thought I'd share. 

https://hastebin.com/share/ajaxiloseb

**Comment by atampy25** [comment]
I honestly have no idea how this error could happen. Is your system unusual in any way (filesystem, OS, etc.)?

**Comment by GarnetSunset** [comment]
NTFS, Windows 11, latest build :(

**Comment by atampy25** [comment]
If you deploy again, does the error appear after the same previous line (`Extracting dependency 0022D892322D674C`)? If so, could you go into the `temp\ALLDEPENDS\0022D892322D674C` folder and send a screenshot of its (and its subfolders') contents?

**Comment by GarnetSunset** [comment]
Appears on the same line and nothing exists in temp because I think the failed install clears temp

**Comment by atampy25** [comment]
Try deleting the cache folder found in the SMF directory and deploying again.

**Comment by GarnetSunset** [comment]
DEBUG	Extracting dependency 00925B1C9F15271B
DEBUG	Extracting dependency 0022D892322D674Cthread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\lib.rs:29:22note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Same issue
